services:
  mern-social:
    container_name: mern-social
    image: mern-social
    restart: always
    environment:
      IP: mern-social-db
    build: ./mern-social
    networks:
      - backend

  mern-social-db:
    container_name: mern-social-db
    image: mongo
    restart: always
    volumes:
      - ./mern-social-db:/data/db
    networks:
      - backend

  nginx:
    image: nginx
    ports:
      - "443:443"
    depends_on:
      - mern-social
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - frontend
      - backend

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_SERVER: mern-social-db
      ME_CONFIG_MONGODB_URL: mongodb://mern-social-db:27017
    depends_on:
      - mern-social-db
    ports:
      - "8081:8081"
    networks:
      - backend
      - frontend

networks:
  backend:
    internal: true
  frontend:
