apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: nginx-crt
              mountPath: /etc/nginx/certs/localhost.crt
              subPath: localhost.crt                                          2 lines ]
            - name: nginx-key
              mountPath: /etc/nginx/private/localhost.key
              subPath: localhost.key
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - name: nginx-crt
          secret:
            secretName: nginx-certs
        - name: nginx-key
          secret:
            secretName: nginx-certs