apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: mern-social
          imagePullPolicy: Never
          env:
          - name: IP
            value: "mern-social-db"
          ports:
          - containerPort: 3000
